# Generated by Django 5.2.1 on 2025-06-02 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_accesibilidade', models.CharField(max_length=250)),
                ('descricion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PropostaVideoxogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricion', models.TextField()),
                ('prezo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idade_recomendada', models.IntegerField(choices=[(3, '3+'), (6, '6+'), (9, '9+'), (12, '12+'), (16, '16+'), (18, '18+')])),
                ('data_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDENTE', max_length=10)),
                ('caratula', models.ImageField(blank=True, null=True, upload_to='propostas')),
                ('alt', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'proposta_videoxogo',
            },
        ),
        migrations.CreateModel(
            name='Videoxogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descricion', models.TextField(max_length=1000)),
                ('prezo', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0, 0)])),
                ('idade_recomendada', models.IntegerField(choices=[(3, '3+'), (6, '6+'), (9, '9+'), (12, '12+'), (16, '16+'), (18, '18+')], default=3)),
                ('caratula', models.ImageField(blank=True, null=True, upload_to='games')),
                ('alt', models.CharField(blank=True, help_text='Descripción alternativa de la carátula para accesibilidad', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xenero', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciasAccesibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesibilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.accesibilidade')),
            ],
        ),
        migrations.CreateModel(
            name='PropostaVideoxogoAccesibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesibilidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restApi.accesibilidade')),
                ('proposta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restApi.propostavideoxogo')),
            ],
            options={
                'db_table': 'proposta_videoxogo_accesibilidade',
                'unique_together': {('proposta', 'accesibilidade')},
            },
        ),
        migrations.AddField(
            model_name='propostavideoxogo',
            name='accesibilidades',
            field=models.ManyToManyField(blank=True, null=True, related_name='propostas', through='restApi.PropostaVideoxogoAccesibilidade', to='restApi.accesibilidade'),
        ),
        migrations.CreateModel(
            name='PropostaVideoxogoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restApi.plataforma')),
                ('proposta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restApi.propostavideoxogo')),
            ],
            options={
                'db_table': 'proposta_videoxogo_plataforma',
                'unique_together': {('proposta', 'plataforma')},
            },
        ),
        migrations.AddField(
            model_name='propostavideoxogo',
            name='plataforma',
            field=models.ManyToManyField(blank=True, null=True, related_name='propostas_plataforma', through='restApi.PropostaVideoxogoPlataforma', to='restApi.plataforma'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('contrasinal', models.CharField(max_length=128)),
                ('imaxe_user', models.ImageField(blank=True, null=True, upload_to='users')),
                ('admin', models.BooleanField(default=False)),
                ('preferencias', models.ManyToManyField(related_name='usuario_preferencias', through='restApi.PreferenciasAccesibilidade', to='restApi.accesibilidade')),
            ],
        ),
        migrations.AddField(
            model_name='propostavideoxogo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='restApi.usuario'),
        ),
        migrations.AddField(
            model_name='preferenciasaccesibilidade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.usuario'),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.usuario')),
                ('videoxogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.videoxogo')),
            ],
            options={
                'unique_together': {('usuario', 'videoxogo')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(related_name='usuarios_favoritos', through='restApi.Favorito', to='restApi.videoxogo'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=1000)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('dislikes', models.IntegerField(blank=True, default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='restApi.usuario')),
                ('videoxogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='restApi.videoxogo')),
            ],
            options={
                'ordering': ['-likes'],
            },
        ),
        migrations.CreateModel(
            name='VideoxogoAccesibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesibilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.accesibilidade')),
                ('videoxogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.videoxogo')),
            ],
            options={
                'unique_together': {('videoxogo', 'accesibilidade')},
            },
        ),
        migrations.AddField(
            model_name='videoxogo',
            name='accesibilidades',
            field=models.ManyToManyField(related_name='videoxogos', through='restApi.VideoxogoAccesibilidade', to='restApi.accesibilidade'),
        ),
        migrations.CreateModel(
            name='VideoxogoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.plataforma')),
                ('videoxogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.videoxogo')),
            ],
            options={
                'db_table': 'restApi_videoxogoPlataform_videoxogoPlataforma',
                'unique_together': {('videoxogo', 'plataforma')},
            },
        ),
        migrations.AddField(
            model_name='videoxogo',
            name='plataforma',
            field=models.ManyToManyField(related_name='videoxogos_plataforma', through='restApi.VideoxogoPlataforma', to='restApi.plataforma'),
        ),
        migrations.CreateModel(
            name='VideoxogoXenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoxogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.videoxogo')),
                ('xenero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.xenero')),
            ],
            options={
                'db_table': 'restApi_videoxogoXenero_videoxogoXenero',
                'unique_together': {('videoxogo', 'xenero')},
            },
        ),
        migrations.AddField(
            model_name='videoxogo',
            name='xenero',
            field=models.ManyToManyField(related_name='videoxogo_xenero', through='restApi.VideoxogoXenero', to='restApi.xenero'),
        ),
        migrations.CreateModel(
            name='PropostaVideoxogoXenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restApi.propostavideoxogo')),
                ('xenero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restApi.xenero')),
            ],
            options={
                'db_table': 'proposta_videoxogo_xenero',
                'unique_together': {('proposta', 'xenero')},
            },
        ),
        migrations.AddField(
            model_name='propostavideoxogo',
            name='xenero',
            field=models.ManyToManyField(blank=True, null=True, related_name='propostas_xenero', through='restApi.PropostaVideoxogoXenero', to='restApi.xenero'),
        ),
        migrations.AlterUniqueTogether(
            name='preferenciasaccesibilidade',
            unique_together={('usuario', 'accesibilidade')},
        ),
    ]
