# Generated by Django 5.2.1 on 2025-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_videoxogo_desarrolladora'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostavideoxogo',
            name='desarrolladora',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
