# Generated by Django 5.2.1 on 2025-06-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0003_propostavideoxogo_desarrolladora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propostavideoxogo',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
