# Generated by Django 5.2.1 on 2025-06-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0004_rename_usuario_propostavideoxogo_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostavideoxogo',
            name='estado',
            field=models.CharField(default='PENDENTE', max_length=10),
        ),
    ]
