# Generated by Django 5.2.1 on 2025-06-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0005_alter_propostavideoxogo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesibilidade',
            name='descricion',
        ),
    ]
