# Generated by Django 5.2.1 on 2025-06-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0006_remove_accesibilidade_descricion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imaxe_user',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='videoxogo',
            name='caratula',
            field=models.ImageField(blank=True, null=True, upload_to='games/'),
        ),
    ]
